# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Generate.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(558, 320)
        MainWindow.setMinimumSize(QtCore.QSize(558, 320))
        MainWindow.setMaximumSize(QtCore.QSize(558, 320))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(220, 55, 151, 21))
        self.radioButton_2.setStyleSheet("font-size: 16px;")
        self.radioButton_2.setObjectName("radioButton_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 170, 81, 21))
        self.label_2.setStyleSheet("font-size: 18px;")
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(10, 210, 421, 20))
        self.lineEdit_2.setStyleSheet("border-radius: 10px;\n"
"background-color: #D3D3D3;\n"
"font-size: 18px;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(220, 10, 111, 21))
        self.label_3.setStyleSheet("font-size: 18px;")
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 20, 151, 16))
        self.label.setStyleSheet("font-size: 18px;")
        self.label.setObjectName("label")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(220, 40, 131, 17))
        self.radioButton.setStyleSheet("font-size: 16px;")
        self.radioButton.setObjectName("radioButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 40, 141, 20))
        self.lineEdit.setStyleSheet("border-radius: 10px;\n"
"background-color: #D3D3D3;\n"
"font-size: 18px;")
        self.lineEdit.setObjectName("lineEdit")
        self.radioButton_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(220, 95, 201, 21))
        self.radioButton_3.setStyleSheet("font-size: 16px;")
        self.radioButton_3.setObjectName("radioButton_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(430, 260, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Time New Roman")
        font.setPointSize(-1)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("font-size: 16px;\n"
"font-family: Time New Roman;")
        self.pushButton.setObjectName("pushButton")
        self.radioButton_4 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_4.setGeometry(QtCore.QRect(220, 70, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setObjectName("radioButton_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 260, 121, 51))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.radioButton_5 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_5.setGeometry(QtCore.QRect(220, 115, 221, 21))
        self.radioButton_5.setStyleSheet("font-size: 16px;")
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_6.setGeometry(QtCore.QRect(220, 135, 241, 21))
        self.radioButton_6.setStyleSheet("font-size: 16px;")
        self.radioButton_6.setObjectName("radioButton_6")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.radioButton_2.setText(_translate("MainWindow", "Only letters (Latin)"))
        self.label_2.setText(_translate("MainWindow", "Password"))
        self.label_3.setText(_translate("MainWindow", "Тип пароля"))
        self.label.setText(_translate("MainWindow", "Characters num"))
        self.radioButton.setText(_translate("MainWindow", "Only numbers"))
        self.radioButton_3.setText(_translate("MainWindow", "Combo(Latin + numbers)"))
        self.pushButton.setText(_translate("MainWindow", "Generate"))
        self.radioButton_4.setText(_translate("MainWindow", "Only letters (Cyrillic)"))
        self.pushButton_2.setText(_translate("MainWindow", "Clear"))
        self.radioButton_5.setText(_translate("MainWindow", "Combo(Cyrillic + numbers)"))
        self.radioButton_6.setText(_translate("MainWindow", "Super Combo"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
